# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_soalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeSoalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_soal', models.CharField(max_length=128, unique=True, verbose_name='kode soal')),
            ],
        ),
        migrations.DeleteModel(
            name='StatusModel',
        ),
    ]
