# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20161110_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSoalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_soal', models.CharField(max_length=128, unique=True, verbose_name='jawaban soal')),
            ],
        ),
        migrations.AddField(
            model_name='soalmodel',
            name='jawaban_soal',
            field=models.CharField(default='', max_length=1024, verbose_name='jawaban_soal'),
        ),
    ]
